### ISSUE TITLE
No Root Folder Found

### ISSUE THREAD

**Issue by EgidioBezerra** [apenasrr/zipsender#3]
I'm having this issue, i'm using debian 12 and Python 3.11.2

```
Add file /storage/apps/zipsender/1-tozip/UNESC/V_DEOS/BASES MORFOL_GICAS/Wagner de Brito Veras/Fisiologia do M_sculo Estriado Esquel_tico-20210607_200227-Meeting Recording.mp4
Creating... 3-toupload/UNESC/output/UNESC-008.rar
Traceback (most recent call last):
  File "/storage/apps/zipsender/zipsender_zip.py", line 344, in <module>
    main()
  File "/storage/apps/zipsender/zipsender_zip.py", line 321, in main
    save_log_folder_structure(
  File "/storage/apps/zipsender/zipsender_zip.py", line 168, in save_log_folder_structure
    string_tree = content_tree.main(dict_tasks_log)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/apps/zipsender/content_tree.py", line 108, in main
    serie_path_relativa = get_serie_folder_path_relative(df_raw["file_path"])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/apps/zipsender/content_tree.py", line 69, in get_serie_folder_path_relative
    raise ValueError("No root folder found")
ValueError: No root folder found
```

**Comment by EgidioBezerra** [comment]
Solved!!

- Don't use python 3.12 or above
- Remember to change to zip if using 7zip!

**Comment by EgidioBezerra** [comment]
The issue remains in debian 12.
